### ISSUE TITLE
CUDA 10.0 sample coredump.

### ISSUE THREAD

**Issue by unix2x** [virtaitech/orion#11]
ISSUE: 客户端运行CUDA sample coredump

[root@client matrixMul]# export ORION_VGPU=1
[root@client matrixMul]# ls
Makefile  matrixMul  matrixMul.cu  matrixMul.o  NsightEclipse.xml  readme.txt
[root@client matrixMul]# ./matrixMul
[Matrix Multiply Using CUDA] - Starting...
VirtaiTech Resource. Build-cuda-bd1163c-20200128_130008
2020-03-29 12:57:50 [INFO] Using Orion resource (fd720053-7d84-483b-bc28-ef52915861df) 01c9c6b1-1049-472e-92f6-09f239dde664 : 192.168.122.112:9960/0/0
Segmentation fault (core dumped)
[root@client matrixMul]#

[root@client matrixMul]# gdb ./matrixMul core.5708
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-114.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /root/NVIDIA_CUDA-10.0_Samples/0_Simple/matrixMul/matrixMul...(no debugging symbols found)...done.
[New LWP 5708]
[New LWP 5709]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./matrixMul'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007ff56117c38a in ?? () from /usr/lib/orion/libcuda.so.1
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 cyrus-sasl-lib-2.1.26-23.el7.x86_64 elfutils-libelf-0.172-2.el7.x86_64 elfutils-libs-0.172-2.el7.x86_64 glibc-2.17-260.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-34.el7.x86_64 libattr-2.4.46-13.el7.x86_64 libcap-2.22-9.el7.x86_64 libcom_err-1.42.9-13.el7.x86_64 libcurl-7.29.0-51.el7.x86_64 libgcc-4.8.5-36.el7.x86_64 libibverbs-17.2-3.el7.x86_64 libidn-1.28-4.el7.x86_64 libnl3-3.2.28-4.el7.x86_64 libselinux-2.5-14.1.el7.x86_64 libssh2-1.4.3-12.el7.x86_64 libstdc++-4.8.5-36.el7.x86_64 libuuid-2.23.2-59.el7.x86_64 nspr-4.19.0-1.el7_5.x86_64 nss-3.36.0-7.el7_5.x86_64 nss-softokn-freebl-3.36.0-5.el7_5.x86_64 nss-util-3.36.0-1.el7_5.x86_64 openldap-2.4.44-20.el7.x86_64 openssl-libs-1.0.2k-16.el7.x86_64 pcre-8.32-17.el7.x86_64 systemd-libs-219-62.el7.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb)

[root@server1 orion]# cat controller.log
time="2020-03-29T12:50:16+08:00" level=info msg="Etcd Server is ready!"
time="2020-03-29T12:50:16+08:00" level=info msg="Creating database connection to http://127.0.0.1:23791"
time="2020-03-29T12:50:16+08:00" level=info msg="Database connection is created."
time="2020-03-29T12:50:16+08:00" level=info msg="Orion CE Controller is launching, listening on 0.0.0.0:9123"
time="2020-03-29T12:50:19+08:00" level=info msg="Received API (method:POST; api version:0.2; data version:0.2) : /device/info "
time="2020-03-29T12:50:19+08:00" level=info msg="Adding new host for NVidia GPU : 192.168.122.111"
time="2020-03-29T12:50:19+08:00" level=info msg="Adding new NVidia GPU to host 192.168.122.111 (GPU-0f0c6ac9-8986-436a-af15-6ef0e315a435; GRID P40-4Q)"
time="2020-03-29T12:52:33+08:00" level=info msg="Received API (method:POST; api version:0.2; data version:0.2) : /device/info "
time="2020-03-29T12:52:33+08:00" level=info msg="Adding new host for NVidia GPU : 192.168.122.112"
time="2020-03-29T12:52:33+08:00" level=info msg="Adding new NVidia GPU to host 192.168.122.112 (GPU-e911a9a4-be4a-46a5-abf5-1eab16e551cc; GRID P40-4Q)"
time="2020-03-29T12:57:50+08:00" level=info msg="Received API (method:GET; api version:0.2; data version:0.2; client ID:; group ID:fd720053-7d84-483b-bc28-ef52915861df) : /service nvidia_vgpu=1"
time="2020-03-29T12:57:50+08:00" level=info msg="Return formated resource : 01c9c6b1-1049-472e-92f6-09f239dde664,192.168.122.112:9960/0/0"
time="2020-03-29T12:57:50+08:00" level=info msg="Received API (method:POST; api version:0.2; data version:0.2; client ID:; group ID:) : /service/01c9c6b1-1049-472e-92f6-09f239dde664/192.168.122.112 "
time="2020-03-29T12:57:50+08:00" level=info msg="Received API (method:PUT; api version:0.2; data version:0.2; client ID:; group ID:) : /service/confirm/01c9c6b1-1049-472e-92f6-09f239dde664 "
time="2020-03-29T12:57:50+08:00" level=info msg="Confirm allocation 01c9c6b1-1049-472e-92f6-09f239dde664 with device : 192.168.122.112/0/0"
time="2020-03-29T12:57:50+08:00" level=info msg="Received API (method:PUT; api version:0.2; data version:0.2; client ID:; group ID:) : /service/release/01c9c6b1-1049-472e-92f6-09f239dde664 "
time="2020-03-29T12:57:50+08:00" level=info msg="Release allocation 01c9c6b1-1049-472e-92f6-09f239dde664 with device : 192.168.122.112/0/0"
time="2020-03-29T12:57:50+08:00" level=info msg="All device in allocation 01c9c6b1-1049-472e-92f6-09f239dde664 is released."
time="2020-03-29T12:58:33+08:00" level=info msg="Received API (method:GET; api version:0.2; data version:0.2; client ID:; group ID:40dcd30a-4ddd-47d2-9cd5-7b8f2681e40f) : /service nvidia_vgpu=1"
time="2020-03-29T12:58:33+08:00" level=info msg="Return formated resource : e8352814-e5d8-4ec4-859f-169a1b844763,192.168.122.112:9960/0/0"
time="2020-03-29T12:58:33+08:00" level=info msg="Received API (method:POST; api version:0.2; data version:0.2; client ID:; group ID:) : /service/e8352814-e5d8-4ec4-859f-169a1b844763/192.168.122.112 "
time="2020-03-29T12:58:33+08:00" level=info msg="Received API (method:PUT; api version:0.2; data version:0.2; client ID:; group ID:) : /service/confirm/e8352814-e5d8-4ec4-859f-169a1b844763 "
time="2020-03-29T12:58:33+08:00" level=info msg="Confirm allocation e8352814-e5d8-4ec4-859f-169a1b844763 with device : 192.168.122.112/0/0"
time="2020-03-29T12:58:33+08:00" level=info msg="Received API (method:PUT; api version:0.2; data version:0.2; client ID:; group ID:) : /service/release/e8352814-e5d8-4ec4-859f-169a1b844763 "
time="2020-03-29T12:58:33+08:00" level=info msg="Release allocation e8352814-e5d8-4ec4-859f-169a1b844763 with device : 192.168.122.112/0/0"
time="2020-03-29T12:58:33+08:00" level=info msg="All device in allocation e8352814-e5d8-4ec4-859f-169a1b844763 is released."
time="2020-03-29T12:58:54+08:00" level=info msg="Received API (method:GET; api version:0.2; data version:0.2; client ID:; group ID:69201de2-cf4c-4913-ba1e-7d481ec536a7) : /service nvidia_vgpu=1"
time="2020-03-29T12:58:54+08:00" level=info msg="Return formated resource : c17a2c9f-b0e2-4b86-b38f-613fadde3534,192.168.122.111:9960/0/0"
time="2020-03-29T12:58:54+08:00" level=info msg="Received API (method:POST; api version:0.2; data version:0.2; client ID:; group ID:) : /service/c17a2c9f-b0e2-4b86-b38f-613fadde3534/192.168.122.111 "
time="2020-03-29T12:58:54+08:00" level=info msg="Received API (method:PUT; api version:0.2; data version:0.2; client ID:; group ID:) : /service/confirm/c17a2c9f-b0e2-4b86-b38f-613fadde3534 "
time="2020-03-29T12:58:54+08:00" level=info msg="Confirm allocation c17a2c9f-b0e2-4b86-b38f-613fadde3534 with device : 192.168.122.111/0/0"
time="2020-03-29T12:58:55+08:00" level=info msg="Received API (method:PUT; api version:0.2; data version:0.2; client ID:; group ID:) : /service/release/c17a2c9f-b0e2-4b86-b38f-613fadde3534 "
time="2020-03-29T12:58:55+08:00" level=info msg="Release allocation c17a2c9f-b0e2-4b86-b38f-613fadde3534 with device : 192.168.122.111/0/0"
time="2020-03-29T12:58:55+08:00" level=info msg="All device in allocation c17a2c9f-b0e2-4b86-b38f-613fadde3534 is released."
[root@server1 orion]# cat server.log
2020-03-29 12:50:14 [INFO] Connecting to Orion Controller 127.0.0.1:9123
2020-03-29 12:50:19 [INFO] Connecting to Orion Controller 127.0.0.1:9123
2020-03-29 12:50:19 [INFO] Successfully connect to Orion Controller.
2020-03-29 12:50:19 [INFO] Report Orion compatible resource to 127.0.0.1:9123
2020-03-29 12:50:19 [INFO] GRID P40-4Q (ID: GPU-0f0c6ac9-8986-436a-af15-6ef0e315a435) is reported to Orion Controller.
2020-03-29 12:50:19 [INFO] Orion Server listens on 192.168.122.111:9960
2020-03-29 12:58:54 [INFO] Creating session 0
2020-03-29 12:58:54 [INFO] Get resource list (group_id:69201de2-cf4c-4913-ba1e-7d481ec536a7) for allocation ID c17a2c9f-b0e2-4b86-b38f-613fadde3534 : nvidia_cuda;192.168.122.111,9960,GPU-0f0c6ac9-8986-436a-af15-6ef0e315a435,0,0,25,1018
2020-03-29 12:58:54 [INFO] Using SHM 491521 for acceleration.
2020-03-29 12:58:55 [INFO] Session 0 exits.

### 测试环境:

3台虚拟机，其中由2个带Nvidia P40 GPU的虚拟机: 192.168.122.111， 192.168.122.112, 192.168.122.111 用来做Server1 和controller，192.168.122.112 为Server2，
另一台虚拟机192.168.122.175用来运行Client。所有服务器均使用RHEL 7.6 Linux。

Server1， Server2 上安装了 CUDA 10.0 并已经运行CUDA Sample测试通过。

git clone 最新的orion master 分支
192.168.122.111 上按文档安装了 Orion server和controller,以及etcd，配置文件如下:
192.168.122.112 部署了 Orion server
以上服务均可以启动成功

systemctl status orion-controller.service
● orion-controller.service - Orion Controller Service
   Loaded: loaded (/etc/systemd/system/orion-controller.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2020-03-27 10:14:44 CST; 2 days ago
 Main PID: 27224 (orion-controlle)
    Tasks: 14
   CGroup: /system.slice/orion-controller.service
           └─27224 /usr/bin/orion-controller start --config-file /etc/orion/controller.yaml

systemctl status oriond
● oriond.service - Orion Server Daemon Service
   Loaded: loaded (/etc/systemd/system/oriond.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2020-03-27 10:14:45 CST; 2 days ago
 Main PID: 27250 (oriond)
    Tasks: 3
   CGroup: /system.slice/oriond.service
           ├─27250 /usr/bin/oriond
           └─27253 /usr/bin/oriond

LOG:
[root@server1 ~]# cat /var/log/orion/controller.log
time="2020-03-29T12:50:16+08:00" level=info msg="Etcd Server is ready!"
time="2020-03-29T12:50:16+08:00" level=info msg="Creating database connection to http://127.0.0.1:23791"
time="2020-03-29T12:50:16+08:00" level=info msg="Database connection is created."
time="2020-03-29T12:50:16+08:00" level=info msg="Orion CE Controller is launching, listening on 0.0.0.0:9123"
time="2020-03-29T12:50:19+08:00" level=info msg="Received API (method:POST; api version:0.2; data version:0.2) : /device/info "
time="2020-03-29T12:50:19+08:00" level=info msg="Adding new host for NVidia GPU : 192.168.122.111"
time="2020-03-29T12:50:19+08:00" level=info msg="Adding new NVidia GPU to host 192.168.122.111 (GPU-0f0c6ac9-8986-436a-af15-6ef0e315a435; GRID P40-4Q)"
time="2020-03-29T12:52:33+08:00" level=info msg="Received API (method:POST; api version:0.2; data version:0.2) : /device/info "
time="2020-03-29T12:52:33+08:00" level=info msg="Adding new host for NVidia GPU : 192.168.122.112"
time="2020-03-29T12:52:33+08:00" level=info msg="Adding new NVidia GPU to host 192.168.122.112 (GPU-e911a9a4-be4a-46a5-abf5-1eab16e551cc; GRID P40-4Q)"
[root@server1 ~]# cat /var/log/orion/server.log
2020-03-29 12:50:14 [INFO] Connecting to Orion Controller 127.0.0.1:9123
2020-03-29 12:50:19 [INFO] Connecting to Orion Controller 127.0.0.1:9123
2020-03-29 12:50:19 [INFO] Successfully connect to Orion Controller.
2020-03-29 12:50:19 [INFO] Report Orion compatible resource to 127.0.0.1:9123
2020-03-29 12:50:19 [INFO] GRID P40-4Q (ID: GPU-0f0c6ac9-8986-436a-af15-6ef0e315a435) is reported to Orion Controller.
2020-03-29 12:50:19 [INFO] Orion Server listens on 192.168.122.111:9960
[root@server1 ~]#

[root@server2 ~]# cat /var/log/orion/server.log
2020-03-29 12:52:33 [INFO] Connecting to Orion Controller 192.168.122.111:9123
2020-03-29 12:52:33 [INFO] Successfully connect to Orion Controller.
2020-03-29 12:52:33 [INFO] Report Orion compatible resource to 192.168.122.111:9123
2020-03-29 12:52:33 [INFO] GRID P40-4Q (ID: GPU-e911a9a4-be4a-46a5-abf5-1eab16e551cc) is reported to Orion Controller.
2020-03-29 12:52:33 [INFO] Orion Server listens on 192.168.122.112:9960
[root@server2 ~]#

配置文件:

**controller.yaml:**

controller:
  listen_ip: 0.0.0.0
  listen_port: 9123
  log_level: info
  log_file: "/var/log/orion/controller.log"
  authentication:
    client-key:
    server-key:
    administrator-key:
database:
  name: etcd
  data-dir: "/root/.orion/etcd"
  listen-client-urls: http://127.0.0.1:23791
  advertise-client-urls: http://127.0.0.1:23791
  listen-peer-urls: http://127.0.0.1:23801
  initial-advertise-peer-urls: http://127.0.0.1:23801
  initial-cluster: etcd=http://127.0.0.1:23801
  initial-cluster-state: new
  initial-cluster-token: Orion-database-cluster

**server.conf**
; this is an example of orion configuration
[server]
    listen_port = 9960
    bind_addr = 192.168.122.111
    enable_kvm = "false"
    enable_shm = "true"
    enable_rdma = "false"
    vgpu_count = 4

[server-nccl]
    comm_id = "127.0.0.1:9970"

[server-log]
    log_with_time = 1
    log_to_screen = 0
    log_to_file = 1
    log_level = INFO
    file_log_level = INFO

[server-shm]
    shm_path_base = "/dev/shm/"
    shm_group_name = "orion"
    shm_user_name = "orion"
    shm_buffer_size = 128

[controller]
    controller_addr = 127.0.0.1:9123

Server 2配置
server.conf
; this is an example of orion configuration
[server]
    listen_port = 9960
    bind_addr = 192.168.122.112
    enable_kvm = "false"
    enable_shm = "true"
    enable_rdma = "false"
    vgpu_count = 4

[server-nccl]
    comm_id = "127.0.0.1:9970"

[server-log]
    log_with_time = 1
    log_to_screen = 0
    log_to_file = 1
    log_level = INFO
    file_log_level = INFO

[server-shm]
    shm_path_base = "/dev/shm/"
    shm_group_name = "orion"
    shm_user_name = "orion"
    shm_buffer_size = 128

[controller]
        controller_addr = 192.168.122.111:9123

Server1, Server2 上创建了用户和组 orion

Client:

[root@client matrixMul]# cat /etc/orion/client.conf
[client-log]
    log_with_time = 1
    log_to_screen = 1
    log_to_file = 1
    log_level = INFO
    file_log_level = INFO

[client-shm]
    shm_path_base = "/dev/shm/"

[controller]
    controller_addr = 192.168.122.111:9123

**Comment by virtaitech** [comment]
请把client.conf 中的log_level 从 INFO 改成 DEBUG， 然后再运行一次。运行后，把controller的log，server的log，还有client的log提交一次。
client的log的位置在 ~/.orion/log/ 目录中，找到最后一个log文件即为对应于最后一次测试的日志。
