### ISSUE TITLE
pod里如果启动两个深度学习进程，会超出vgpu的limit的个数和缓存的大小，请问这种情况如何限制

### ISSUE THREAD

**Issue by kiddyu** [virtaitech/orion#13]

**Comment by virtaitech** [comment]
在启动前，设置 export ORION_RES_GROUP=BOX 可以把一个POD里面的多个进程当作一个资源组来申请“一份”资源，从而避免多个进程申请多份资源。不过请注意，一个资源组内的资源竞争/冲突，需要应用本身去解决。
