### ISSUE TITLE
failed to run command '.origin-controller':permission denied 

### ISSUE THREAD

**Issue by dc-wangjn** [virtaitech/orion#14]
i obey the instruction to configure the orion controller using command:
### nohup ./orion-controller start --config-file controller.yaml &
but output the error described as titile:
failed to run command '.origin-controller':permission denied 
could any one help me handle this problem?

**Comment by virtaitech** [comment]
Please use ls -l orion-controller to see whether the binary is executable.
if not, use chmod + x orion-controller to let it be executable.

**Comment by dc-wangjn** [comment]
thanks for your reply and i have solved this problem successfully.
By the way, the defult path of log file is:
"/var/log/orion/controller.log"
which need to be modified as 
"controller.log" to avoid the "no such file or directory " error
and generate the expected output as QUICK START said.
