### ISSUE TITLE
Orion-client Connection to server is broken.

### ISSUE THREAD

**Issue by lvchentao** [virtaitech/orion#16]
使用官方镜像跑一个simpleMultiGPU任务，提示信息为

![image](https://user-images.githubusercontent.com/39354472/96850964-095c0500-148a-11eb-8f71-3325de593f14.png)

orion-server 日志报错为：
![image](https://user-images.githubusercontent.com/39354472/96851277-6ce63280-148a-11eb-9484-d3784b0341f7.png)

环境信息：
使用hostIPC模式，访问本地Orion-server
k8s-1.16

请问可能是什么原因呢？

**Comment by virtaitech** [comment]
请在Orion Server 和 Orion Client镜像里面的配置文件  /etc/orion/server.conf  和  /etc/orion/client.conf 里面的log level 改成 DEBUG再试一次，看看打印的详细日志是什么

**Comment by lvchentao** [comment]
感谢回复！
打印的DEBUG日志，server端的几乎没变
![image](https://user-images.githubusercontent.com/39354472/96946279-7fa44a00-1512-11eb-8fa1-13a8b0f73d41.png)


Client端的如下：
![image](https://user-images.githubusercontent.com/39354472/96946265-75824b80-1512-11eb-8c7e-932063abf0a1.png)


controller 日志没发现异常：
![image](https://user-images.githubusercontent.com/39354472/96946306-9480dd80-1512-11eb-85e4-09f1cae1962d.png)


使用wireshark抓包 server 以及 client的tcp包如下：
![image](https://user-images.githubusercontent.com/39354472/96945864-7070cc80-1511-11eb-9058-fb08623237d4.png)

![image](https://user-images.githubusercontent.com/39354472/96945900-89797d80-1511-11eb-8446-aef95730a609.png)
