### ISSUE TITLE
cuda-wrapper does not work

### ISSUE THREAD

**Issue by iteratorlee** [virtaitech/orion#19]
After replacing the original libcudart_static.a with /cuda-wrapper/cuda-10.1/libcudart_static.a.10.1, I re-built tensorflow serving from source. However, when I used `readelf -Ws tensorflow_model_serer | grep cuMemAlloc` to dig into the ELF structure of tf servable, I found that some APIs such as `cuMemAlloc` and `cuMemGetInfo` are still static linked. How to fix it? Or did I use the cuda-wrapper in a wrong manner otherwise?

**Comment by virtaitech** [comment]
Yes it is still static linked, while in the wrapper a dynamic implementation is loaded.

**Comment by iteratorlee** [comment]
> Yes it is still static linked, while in the wrapper a dynamic implementation is loaded.

So the customized `libcudart_static.a.10.1` is a full implementation of all the APIs in the old `libcudart_static.a` yet in a dynamic way?

**Comment by virtaitech** [comment]
Not all of it. The version is originally for some specified versions of TensorFlow and PyTorch. The latest support is from https://www.virtaitech.com/
