### ISSUE TITLE
部署k8s-device-plugin，启动的日志报错

### ISSUE THREAD

**Issue by zwqzhangweiqiang** [virtaitech/orion#21]
![图片](https://user-images.githubusercontent.com/14371089/147575508-e4705dc3-9b62-402d-b7c7-3bcfaa827450.png)
请问这是什么原因？

**Comment by virtaitech** [comment]
这个127.0.0.1 只是默认配置。启动容器时要配置环境变量  ORION_CONTROLLER 指向实际部署的 Controller 的位置。
