### ISSUE TITLE
代码运行时，一直报如下orion resource has limited support for fork 的warning，会是什么原因，能取消warning吗

### ISSUE THREAD

**Issue by kbmannnn** [virtaitech/orion#22]
![8e76a222eefa5e38f2964513e445d0b](https://user-images.githubusercontent.com/87804231/150494792-516315df-4191-4960-90cb-df03476090bb.jpg)

**Comment by virtaitech** [comment]
According to Nvidia document, CUDA dose not guarantee the correctness if an application fork child process after calling CUDA API. However, some applications like PyTorch do that. So it really relies on the detail application implementation to keep the correctness in this case. Orion also followes the CUDA document  and print the warning message. 

If you pretty sure it is ok, then you can edit /etc/orion/client.conf to close the "print to screen" option so the warning message won't be printed on the screen.  If you want a better support to the case doing "fork", please contact us by BD@virtaitech.com to use our latest version of Orion.

**Comment by kbmannnn** [comment]
> According to Nvidia document, CUDA dose not guarantee the correctness if an application fork child process after calling CUDA API. However, some applications like PyTorch do that. So it really relies on the detail application implementation to keep the correctness in this case. Orion also followes the CUDA document and print the warning message.
> 
> If you pretty sure it is ok, then you can edit /etc/orion/client.conf to close the "print to screen" option so the warning message won't be printed on the screen. If you want a better support to the case doing "fork", please contact us by [BD@virtaitech.com](mailto:BD@virtaitech.com) to use our latest version of Orion.
