### ISSUE TITLE
请问是否支持docker容器内使用OpenGL硬件加速运行3D仿真软件

### ISSUE THREAD

**Issue by LeehanLee** [virtaitech/orion#26]
使用场景：

宿主机是centos7，安装了docker 19以上，安装了nvidia docker 2.5。
现构建了一个docker镜像，该镜像启动容器时将会启动一个xserver，并启动gnome桌面，启动vnc server将桌面可以被用户通过vnc viewer看到。可是存在一个问题，虽然在启动容器时参数有 --gpus device=1 且在该容器内的桌面打开 terminal 运行 nvidia-smi 后也可以看到启动时传递到容器的显卡，但是在这个桌面启动的3D软件就是无法使用GPU，例如webots和gazebo。这两个3D仿真软件在这种情况下，要么是使用软件加速的OpenGL来渲染（其实是基于CPU模拟的），卡顿非常严重，要么是直接提示未检查到显卡，然后拒绝运行并自动退出。这两个3D仿真软件都是需要使用OpenGL硬件加速才可以正常运行的。

也考虑过nvidia的vgpu方案，但是验证的时候发现nvidia vgpu方案仅对Citrix，Vmware，KVM等虚拟机平台提供直接支持，不直接支持docker。

请问orion有没有某种方式可以支持这种场景？

**Comment by virtaitech** [comment]
The version in Github dose not support OpenGL. A later version will work to support OpenGL. You could contact with us by email BD@virtaitech.com.
