### ISSUE TITLE
容器化部署orion-plugin 时pod  状态为CrashLoopBackOff

### ISSUE THREAD

**Issue by zqz199** [virtaitech/orion#27]
![image](https://user-images.githubusercontent.com/97715065/177499186-b678c61a-aec2-49f0-baf7-da503b192486.png)
![image](https://user-images.githubusercontent.com/97715065/177499286-cdf3b611-50e1-4cb6-9a83-80ee9b0665f7.png)

**Comment by zqz199** [comment]
我本机的环境x86-64，拉取的latest镜像是amd64的，是不是跟这个有关系

**Comment by virtaitech** [comment]
这个问题没有关系。建议使用 docker run 来运行一下容器，看看是否可行。排除是 k8s 的问题，还是docker 运行环境的问题。

**Comment by zqz199** [comment]
![image](https://user-images.githubusercontent.com/97715065/177698826-8aceb96e-3d53-469f-af85-f4a0de35ccb7.png)
一样的报错

**Comment by zqz199** [comment]
![image](https://user-images.githubusercontent.com/97715065/177926868-85c93c5b-04fb-4147-8b9e-d7c23003c363.png)

我换了服务器，重新配置的集群，orion-plugin还是一样的报错，看来跟环境无关，应该是镜像的问题

**Comment by virtaitech** [comment]
安装 nVidia docker runtime了吗

**Comment by zqz199** [comment]
我本机环境在开始部署orion之前已经安装过k8s-device-plugin插件，原本就配置了nvidia-contianer-runtime，我看到镜像仓库中有其他版本，逐个往下试了下，换成2.2版本，问题解决。感谢帮助
![image](https://user-images.githubusercontent.com/97715065/178095365-f09a113a-7580-4c96-bcb6-4c217369432e.png)
![image](https://user-images.githubusercontent.com/97715065/178095373-5ad5348f-2139-4234-8c54-ef90b0834d91.png)
