### ISSUE TITLE
场景选择

### ISSUE THREAD

**Issue by SunshineJZJ** [virtaitech/orion#3]
您好 有两个问题麻烦请问贵公司：
目前实验室有一台服务器，实验室人员想通过访问虚拟gpu的方式使用。
对于提供的三种场景：
场景一：Docker 容器中使用本地节点GPU资源
场景二：KVM 虚拟机中使用本地节点GPU资源
场景三：在没有GPU的节点上使用远程节点上的GPU资源

请问我应该选择哪种方案比较好呢？ 

还有一个问题是  场景三是仅限于同一局域网中使用吗？

**Comment by grizzzzzzzzzzly** [comment]
您好：

如果贵公司实验室人员平时的工作模式是ssh登录到带GPU的服务器上进行，那么选择前两种场景（本地Docker容器或KVM虚拟机）并使用本地共享内存进行数据传输，可以获得最好的性能。
Docker容器和KVM虚拟机下vGPU的性能是几乎一样的，所以二者之间的选择就取决于实验环境/应用的需求了。

如果工作模式需要登录到不带GPU的节点上使用其余节点上的GPU，那么只能选择第三种场景来使用。如果实验室配备了RDMA网络，vGPU的性能是接近于本地GPU的。如果只有TCP网络，
那么会有一定的性能损失。

远程使用GPU资源不限于同一局域网中，我们测试过远程使用云端GPU。不过，如果对性能有要求，还是应该在同一局域网内，通过RDMA网络使用远程vGPU。

祝好！

发件人: SunshineJZJ <notifications@github.com>
发送时间: 2019年8月26日 12:24
收件人: virtaitech/orion <orion@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [virtaitech/orion] 场景选择 (#3)


您好 有两个问题麻烦请问贵公司：
目前实验室有一台服务器，实验室人员想通过访问虚拟gpu的方式使用。
对于提供的三种场景：
场景一：Docker 容器中使用本地节点GPU资源
场景二：KVM 虚拟机中使用本地节点GPU资源
场景三：在没有GPU的节点上使用远程节点上的GPU资源

请问我应该选择哪种方案比较好呢？

还有一个问题是 场景三是仅限于同一局域网中使用吗？

**Comment by SunshineJZJ** [comment]
很详细的讲解 非常感谢！

**Comment by grizzzzzzzzzzly** [comment]
Close due to inactivity over the last week.
