### ISSUE TITLE
CUDA 10 支持？

### ISSUE THREAD

**Issue by nlnjnj** [virtaitech/orion#5]
如题，请问是否有支持CUDA10的计划呢，有的话是否有具体时间安排？

**Comment by virtaitech** [comment]
您好。对于cuda10的支持内部测试已经完成。近日就会更新到Github上。

发件人: nlnjnj <notifications@github.com>
发送时间: 2019年8月30日 10:20
收件人: virtaitech/orion <orion@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [virtaitech/orion] CUDA 10 支持？ (#5)


如题，请问是否有支持CUDA10的计划呢，有的话是否有具体时间安排？
