### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by SolarisYan** [virtaitech/orion#6]
Hi there, where/how can I get the source code, please?

**Comment by virtaitech** [comment]
Hi, Solaris. The source code is not ready for open source yet.

**Comment by SolarisYan** [comment]
OK, Is there a plan to open the source code,please?

**Comment by virtaitech** [comment]
Not yet.

**Comment by grizzzzzzzzzzly** [comment]
Closed due to inactivity over the last week.
