### ISSUE TITLE
分布式配置执行程序失败

### ISSUE THREAD

**Issue by huihuiwe** [virtaitech/orion#7]
在一号物理机上配置client，2号物理机上配置controller和server，检测client的runtime，可以获取vgpu的信息，但是执行 ./deviceQuery报错：Segmentation fault (core dumped)。请问原因是什么？

日志信息：
time="2019-11-28T10:21:09+08:00" level=info msg="Received API (method:GET; api version:0.2; data version:0.2; client ID:; group ID:05c1d3d5-9855-4712-9b1b-9f8946b96085) : /service nvidia_vgpu=2&memory=4096"
time="2019-11-28T10:21:09+08:00" level=info msg="Return formated resource : 76f6a1c4-6880-4702-93b0-15b88775af1e,192.168.207.128:9960/0/0,192.168.207.128:9960/1/0"
time="2019-11-28T10:21:09+08:00" level=info msg="Received API (method:POST; api version:0.2; data version:0.2; client ID:; group ID:) : /service/76f6a1c4-6880-4702-93b0-15b88775af1e/192.168.207.128 "
time="2019-11-28T10:21:09+08:00" level=info msg="Received API (method:PUT; api version:0.2; data version:0.2; client ID:; group ID:) : /service/confirm/76f6a1c4-6880-4702-93b0-15b88775af1e "
time="2019-11-28T10:21:09+08:00" level=info msg="Confirm allocation 76f6a1c4-6880-4702-93b0-15b88775af1e with device : 192.168.207.128/0/0"
time="2019-11-28T10:21:09+08:00" level=info msg="Received API (method:PUT; api version:0.2; data version:0.2; client ID:; group ID:) : /service/confirm/76f6a1c4-6880-4702-93b0-15b88775af1e "
time="2019-11-28T10:21:09+08:00" level=info msg="Confirm allocation 76f6a1c4-6880-4702-93b0-15b88775af1e with device : 192.168.207.128/1/0"
time="2019-11-28T10:21:13+08:00" level=info msg="Received API (method:PUT; api version:0.2; data version:0.2; client ID:; group ID:) : /service/release/76f6a1c4-6880-4702-93b0-15b88775af1e "
time="2019-11-28T10:21:13+08:00" level=info msg="Release allocation 76f6a1c4-6880-4702-93b0-15b88775af1e with device : 192.168.207.128/0/0"
time="2019-11-28T10:21:13+08:00" level=info msg="Received API (method:PUT; api version:0.2; data version:0.2; client ID:; group ID:) : /service/release/76f6a1c4-6880-4702-93b0-15b88775af1e "
time="2019-11-28T10:21:13+08:00" level=info msg="Release allocation 76f6a1c4-6880-4702-93b0-15b88775af1e with device : 192.168.207.128/1/0"
time="2019-11-28T10:21:13+08:00" level=info msg="All device in allocation 76f6a1c4-6880-4702-93b0-15b88775af1e is released."

**Comment by virtaitech** [comment]
你试试在deviceQuery目录里面用下面命令看看是否动态连接了CUDA的runtime 库
ldd deviceQuery | grep libcu

如果没有显示找到类似于libcudart 这样的库，那么就是编译的时候静态链接了CUDA的库。这个时候我们的vGPU虚拟环境会不生效，它会找物理设备，就会出错。如果时这个原因，需要改一下编译选项，改成动态链接CUDA，重新编译就好了。

**Comment by huihuiwe** [comment]
使用 ldd deviceQuery | grep libcu，没有任何显示。
执行cp libcudart_static.a.10.0 /usr/local/cuda-10.0/lib64/libcudart_static.a ，编译使用 
ldd deviceQuery | grep libcu，也没有任何显示。

后来在makeFile文件中nvcc的末尾添加了 -cudart=shared ，编译之后重新查看，有了libcudart的库，不过执行 ./deviceQuery还是有这个问题：Segmentation fault (core dumped)，请问还有可能是什么原因?

**Comment by grizzzzzzzzzzly** [comment]
您好，这种情况下我们需要查看 Orion Server 和 Orion Client 端的日志，麻烦您将它们粘贴出来：

Orion Server 端：

- 主日志：/var/log/orion/server.log
- 单次运行日志：/var/log/orion/session 下面，最新的一条日志 （用 ll -rt 命令，最下面的一条就是最新的）

Orion Client 端：

- $HOME/.orion/log 下面最新的一条日志 （用 ll -rt 命令，最下面的一条就是最新的）

**Comment by huihuiwe** [comment]
多谢，看到您提醒查看server端的日志，发现了问题，shm没有设为false。

client端日志：
1725726117738:	2019-11-28 13:57:35 [INFO] Using Orion resource (a7f66b88-fac1-44f3-ae8e-11245e751b6d) 693e4564-2fa6-418b-bfeb-539d4007286e : 192.168.207.128:9960/0/0


server端日志：

330504051051690:	2019-11-28 13:57:35 [INFO] Environment has been cleaned.
330504055369274:	2019-11-28 13:57:35 [INFO] Resource successfully confirmed with controller
330504055618742:	2019-11-28 13:57:35 [INFO] Final virtual gpu list <vID:pID:mbSize>: 0:0:11441, begin to initialize CUDA device manager
330515001946164:	2019-11-28 13:57:40 [INFO] Registered Orion vGPU 0 on physical GPU 0.
330515002125032:	2019-11-28 13:57:40 [INFO] Architecture initialization is done. Resource is confirmed.
330515033928378:	2019-11-28 13:57:40 [INFO] Launching SHM workers (S-000) ...
330515404589965:	2019-11-28 13:57:40 [INFO] Client heartbeat is broken.
330515406632237:	2019-11-28 13:57:40 [INFO] Resources released successfully

**Comment by grizzzzzzzzzzly** [comment]
您好，请问 deviceQuery 是 NVIDIA CUDA Samples 里的 1_Utilities

> 多谢，看到您提醒查看server端的日志，发现了问题，shm没有设为false。
> 
> client端日志：
> 1725726117738: 2019-11-28 13:57:35 [INFO] Using Orion resource (a7f66b88-fac1-44f3-ae8e-11245e751b6d) 693e4564-2fa6-418b-bfeb-539d4007286e : 192.168.207.128:9960/0/0
> 
> server端日志：
> 
> 330504051051690: 2019-11-28 13:57:35 [INFO] Environment has been cleaned.
> 330504055369274: 2019-11-28 13:57:35 [INFO] Resource successfully confirmed with controller
> 330504055618742: 2019-11-28 13:57:35 [INFO] Final virtual gpu list vID:pID:mbSize: 0:0:11441, begin to initialize CUDA device manager
> 330515001946164: 2019-11-28 13:57:40 [INFO] Registered Orion vGPU 0 on physical GPU 0.
> 330515002125032: 2019-11-28 13:57:40 [INFO] Architecture initialization is done. Resource is confirmed.
> 330515033928378: 2019-11-28 13:57:40 [INFO] Launching SHM workers (S-000) ...
> 330515404589965: 2019-11-28 13:57:40 [INFO] Client heartbeat is broken.
> 330515406632237: 2019-11-28 13:57:40 [INFO] Resources released successfully

您好，现在关闭 shm_enable 选项后，是可以正常通过 TCP/RDMA 访问远端 Orion vGPU 吗？

感谢您的反馈，后续我们也会加强对这种情况下配置不正确的检测，自动回退到使用网络的模式。

**Comment by huihuiwe** [comment]
是的，可以正常访问。

还有一个问题，当前作为client端的物理机安装了cuda环境，如果在没有安装cuda的情况下，执行 
./install-client-10.0后，可以使用nvcc 对 .cu文件进行编译、运行吗？

**Comment by grizzzzzzzzzzly** [comment]
> 是的，可以正常访问。
> 
> 还有一个问题，当前作为client端的物理机安装了cuda环境，如果在没有安装cuda的情况下，执行
> ./install-client-10.0后，可以使用nvcc 对 .cu文件进行编译、运行吗？

如果物理机上原本没有安装 CUDA，那么安装了 Orion Client Runtime 后是不能使用 nvcc 编译的，它是 CUDA SDK 的组件。

**Comment by huihuiwe** [comment]
好的，谢谢啦

**Comment by huihuiwe** [comment]
你好，现在有两台物理机，1号物理机上配置client，2号物理机上配置controller和server。

想同时使用两台物理机上的gpu，然后在1号物理机上也安装server，请问怎么让client获取两台物理机上的vgpu?

**Comment by virtaitech** [comment]
一个client同时使用多台物理机上的GPU，这个功能计划在后面的版本公开，请关注我们的更新。
