### ISSUE TITLE
请问有支持图形渲染能力的计划吗？

### ISSUE THREAD

**Issue by ZYStone** [virtaitech/orion#8]
另外，当前版本NVIDIA的NVENC和NVDEC支持吗？ 👍

**Comment by virtaitech** [comment]
当前版本尚未支持，请关注我们后续的更新。

**Comment by LeehanLee** [comment]
时间来到了2021年10月底，请问目前有规划支持OpenGL相关的图形渲染能力吗？

**Comment by virtaitech** [comment]
谢谢您的关注。这方面的信息是有更新的。请和我们的官方邮箱 BD@virtaitech.com 联系获取关于我们最新的产品情况。
